version: "3.8"
services:
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: db_mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "#Deneme123"
      ACCEPT_EULA: "Y"

  app:
    build: .
    container_name: spring
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
    depends_on:
      - db